sudo: required
dist: trusty

script:
  - bash -xve ./test/travis_ros_install.bash
  - source ~/catkin_ws/devel/setup.bash
  - bash -xve ./test/travis_package_make.bash
  - source ~/catkin_ws/devel/setup.bash
  - bash -xve ./test/travis_prepare_dummy_files.bash
  - source ~/catkin_ws/devel/setup.bash
  - bash -xve ./test/travis_bootstrap.bash
  - source ~/catkin_ws/devel/setup.bash
  - rostest pimouse_monitor pimouse_monitor.launch
